apiVersion: v1
kind: Service
metadata:
  name: java
spec:
  selector:
    app: java
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
    nodePort: 32083
  type: NodePort
  #loadBalancerIP: 10.10.9.219

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp12345
  labels:
    app: java
    tier: frontend
spec:
  selector:
    matchLabels:
      app: java
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: java
        tier: frontend
    spec:
      containers:
      - name: webapp12345
        image: mrchelsea/aishi1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
